

POST http://localhost:3000/register
Content-Type: application/json

{
    "userId": "93e0acda1581837994095",
    "firstName": "aamir",
    "lastName": "khan",
    "email": "amirkhan12@gmail.com",
    "password": "qwertyuiop",
    "post": "hello aamir ! <br> welcome to vishwas Oauth Signin"
}

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "amirkhan12@gmail.com",
    "password": "qwertyuiopa"
}

###

GET http://localhost:3000/getPost
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiJmdW5jdGlvbiBzdWIoKSB7IFtuYXRpdmUgY29kZV0gfSIsImlhdCI6MTU4MTc5MTM0OH0.VP77e02GcNbSX3XKEcQY8k4KC1F3YQqZ_IwNsuUUqIU
