

GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE1ODA4MzMxMjEsImV4cCI6MTU4MDgzMzE0Nn0.QJ0tKxTezLx-v3SYBqpnmUuzBWEKKzsIyyXPBOKdrGo

###

POST http://localhost:3000/login
Content-Type: application/json

{
    "username": "vishwas",
    "password": "crazy"
}
###
POST http://localhost:3000/users/login
Content-Type: application/json

{
    "username": "vishwas",
    "password": "crazy"
}


###
DELETE http://localhost:3000/logout
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYW1teSIsImlhdCI6MTU4MDcxODM4OH0.5Yufjm0nCk9KlpWJ0vVDeSjnLSEJe7LC5QLayUslo9Q"
}

###
POST http://localhost:3000/token
Content-Type: application/json

{
    "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InZpc2h3YXMiLCJwYXNzd29yZCI6IiQyYiQxMCRQcy92c2dRY2hXU2Jaay5kOWUzRUxlVThyaXlQR2FDS3NYZGRqV0QxWkw0RExMcGpXV3ZYcSIsImlhdCI6MTU4MDgzMzA4N30.bSjyeDT1fpI82jqIbf5DDtqsQEieZx5eofndgtzfwyM"
}

###
GET http://localhost:3000/token
Content-Type: application/json
